---
version: 2.1

orbs:
    codecov: codecov/codecov@1.0.5
    browser-tools: circleci/browser-tools@0.1.3
    win: circleci/windows@2.4.0

jobs:
    build:
        docker:
            - image: circleci/node:10.15.3-browsers
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-3-{{ checksum "yarn.lock" }}
            - browser-tools/install-chrome:
                  replace-existing: true
            - run: yarn install --frozen-lockfile
            - run: yarn build
            - run: yarn lint:ci
            - run: yarn test:ci
            - run: yarn test:e2e-ci
            - codecov/upload:
                  file: reports/coverage/*.json
                  flags: frontend,backend
            - store_test_results:
                  path: reports
            - store_artifacts:
                  path: reports
            - store_artifacts:
                  path: errorShots
            - save_cache:
                  key: dependency-cache-3-{{ checksum "yarn.lock" }}
                  paths:
                      - node_modules
                      - ~/.cache/yarn
            - persist_to_workspace:
                  root: .
                  paths:
                      - .git
                      - package.json
                      - oclif.manifest.json
                      - yarn.lock
                      - README.md
                      - bin
                      - dist
                      - modules
                      - lib
#   "pack and publish":
#     docker:
#       - image: circleci/node:10.15.3
#     steps:
#       - attach_workspace:
#           at: .
#       - restore_cache:
#           key: dependency-cache-3-{{ checksum "yarn.lock" }}
#       - run: sudo apt-get update && sudo apt-get install -y p7zip-full
#       - run: yarn oclif-dev pack
#       # - run: yarn oclif-dev pack -t linux-x64,win32-x64,darwin-x64
#       - run: yarn oclif-dev publish
#   "pack deb and publish":
#     docker:
#       - image: circleci/node:10.15.3
#     steps:
#       - attach_workspace:
#           at: .
#       - restore_cache:
#           key: dependency-cache-3-{{ checksum "yarn.lock" }}
#       - run: sudo apt-get update && sudo apt-get install -y apt-utils
#       - run: sudo -E /bin/bash -c "cp -R /home/circleci/.cache /usr/local/share && yarn oclif-dev pack:deb"
#       - run: yarn oclif-dev publish:deb
#   "pack macos and publish":
#     macos:
#       xcode: "10.0.0"
#     steps:
#       - attach_workspace:
#           at: .
#       - restore_cache:
#           key: dependency-cache-3-{{ checksum "yarn.lock" }}
#       - run: yarn oclif-dev pack:macos
#       - run: yarn oclif-dev publish:macos
#   "pack win and publish":
#     docker:
#       - image: circleci/node:10.15.3
#     steps:
#       - attach_workspace:
#           at: .
#       - restore_cache:
#           key: dependency-cache-3-{{ checksum "yarn.lock" }}
#       - run: sudo apt-get update && sudo apt-get install -y nsis p7zip-full
#       - run: yarn oclif-dev pack:win
#       - run: yarn oclif-dev publish:win

    build-and-test-win:
        executor: win/default
        environment:
            # alias variable created by auth and referenced by test framework
            - SFDC_ALIAS: local-dev-user
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-win-{{ checksum "yarn.lock" }}
            - run:
                  shell: bash.exe
                  command: |
                      node --version
                      npm install -g sfdx-cli@latest
                      sfdx --version
            - run:
                  name: 'Authenticate to local dev testing org'
                  shell: bash.exe
                  command: |
                      echo $SFDC_JWT_KEY | base64 --decode > localdev.key
                      sfdx force:auth:jwt:grant --clientid ${SFDC_CLIENTID} --username ${SFDC_USERNAME} --setalias ${SFDC_ALIAS} --jwtkeyfile $PWD/localdev.key --setdefaultusername --setdefaultdevhubusername
                      sfdx force:auth:list
            - run:
                  shell: bash.exe
                  command: |
                      choco install googlechrome --ignore-checksums
            - run: yarn install --frozen-lockfile
            - run: yarn build
            - run: yarn test:ci
            # - run:
            #       shell: bash.exe
            #       command: |
            #           yarn test:e2e-ci
            - store_test_results:
                  path: reports
            - store_artifacts:
                  path: reports
            - store_artifacts:
                  path: errorShots
            - save_cache:
                  key: dependency-cache-win-{{ checksum "yarn.lock" }}
                  paths:
                      - node_modules
                      - ~/.cache/yarn

workflows:
    version: 2.1
    master:
        jobs:
            - 'build'
        #   - "pack and publish":
        #       requires:
        #         - build
        #   - "pack:deb and publish":
        #       requires:
        #         - build
        # - "pack:macos and publish":
        #     requires:
        #       - build
        #   - "pack:win and publish":
        #       requires:
        #         - build

    build_win:
        jobs:
            - build-and-test-win:
                  context: local-dev-gs0
            - build-and-test-win:
                  context: local-dev-r2
