---
version: 2.1

orbs:
    # Code Coverage
    codecov: codecov/codecov@1.0.5
    # For Installing Browsers
    browser-tools: circleci/browser-tools@0.1.3
    # For Testing on windows
    win: circleci/windows@2.4.0

defaults: &defaults
    working_directory: ~/lwc-dev-server
    docker:
        - image: circleci/node:lts-browsers

jobs:
    build-and-test-linux:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-linux-{{ checksum "yarn.lock" }}
            - browser-tools/install-chrome:
                  replace-existing: true
            - run: yarn install --frozen-lockfile
            - run: yarn build
            - run: yarn lint:ci
            - run: yarn test:ci
            - run: yarn test:e2e-ci
            - codecov/upload:
                  file: reports/coverage/*.json
                  flags: frontend,backend
            - store_test_results:
                  path: reports
            - store_artifacts:
                  path: reports
            - store_artifacts:
                  path: errorShots
            - save_cache:
                  key: dependency-cache-linux-{{ checksum "yarn.lock" }}
                  paths:
                      - node_modules
                      - ~/.cache/yarn
            # Commented out till we need to process the assets after the fact.
            # Typically in like a deploy step.
            # - persist_to_workspace:
            #       root: .
            #       paths:
            #           - .git
            #           - package.json
            #           - oclif.manifest.json
            #           - yarn.lock
            #           - README.md
            #           - bin
            #           - dist
            #           - modules
            #           - lib
    build-and-test-win:
        executor: win/default
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-win-{{ checksum "yarn.lock" }}
            - browser-tools/install-chrome:
                  replace-existing: true
            - run: yarn install --frozen-lockfile
            - run: yarn build
            - run: yarn test:ci
            - run: yarn test:e2e-ci
            - store_test_results:
                  path: reports
            - store_artifacts:
                  path: reports
            - store_artifacts:
                  path: errorShots
            - save_cache:
                  key: dependency-cache-win-{{ checksum "yarn.lock" }}
                  paths:
                      - node_modules
                      - ~/.cache/yarn

workflows:
    version: 2.1
    build_and_test:
        jobs:
            - build-and-test-linux
            - build-and-test-win
