---
version: 2.0

jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-3-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn lint
      - run: yarn test
      - store_test_results:
          path: reports
      - save_cache:
          key: dependency-cache-3-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
            - ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths:
            - .git
            - package.json
            - oclif.manifest.json
            - yarn.lock
            - README.md
            - bin
            - dist
            - modules
            - lib
  "pack and publish":
    docker:
      - image: circleci/node:10.15.3
    steps:  
      - attach_workspace:
          at: .
      - restore_cache:
          key: dependency-cache-3-{{ checksum "yarn.lock" }}
      - run: sudo apt-get update && sudo apt-get install -y p7zip-full
      - run: yarn oclif-dev pack
      # - run: yarn oclif-dev pack -t linux-x64,win32-x64,darwin-x64
      - run: yarn oclif-dev publish
  "pack:deb and publish":
    docker:
      - image: circleci/node:10.15.3
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: dependency-cache-3-{{ checksum "yarn.lock" }}
      - run: sudo yarn oclif-dev pack:deb
      - run: yarn oclif-dev publish:deb
  "pack:macos and publish":
    macos:
      xcode: "10.0.0"
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: dependency-cache-3-{{ checksum "yarn.lock" }}
      - run: yarn oclif-dev pack:macos
      - run: yarn oclif-dev publish:macos
  "pack:win and publish":
    docker:
      - image: circleci/node:10.15.3
    steps:
      - attach_workspace:
          at: .
      - restore_cache:
          key: dependency-cache-3-{{ checksum "yarn.lock" }}
      - run: sudo apt-get update && sudo apt-get install -y makensis
      - run: yarn oclif-dev pack:win
      - run: yarn oclif-dev publish:win

workflows:
  version: 2
  master:
    jobs:
      - "build"
      - "pack and publish":
          requires: 
            - build
      - "pack:deb and publish":
          requires: 
            - build
      - "pack:macos and publish":
          requires: 
            - build
      - "pack:win and publish":
          requires: 
            - build

