---
# The following environment variables are required in the 'vscode-test' context
# when running tests for Windows:
#     SFDX_CI_LOCALDEV_CLIENTID -- connected app client ID for localdev org
#     SFDX_CI_LOCALDEV_JWTKEY   -- private key for the connected app (base64 encoded)
#     SFDX_CI_LOCALDEV_USERNAME -- username of an authorized user of the localdev org
version: 2.1

orbs:
    # Code Coverage
    codecov: codecov/codecov@1.0.5
    # For Installing Browsers
    browser-tools: circleci/browser-tools@0.1.3
    # For Testing on windows
    win: circleci/windows@2.4.0

defaults: &defaults
    working_directory: ~/lwc-dev-server
    docker:
        - image: circleci/node:lts-browsers

jobs:
    build-and-test-linux:
        <<: *defaults
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-linux-{{ checksum "yarn.lock" }}
            - browser-tools/install-chrome:
                  replace-existing: true
            - run: yarn install --frozen-lockfile
            - run: yarn build
            - run: yarn lint:ci
            - run: yarn test:ci
            - run: yarn test:e2e-ci
            - codecov/upload:
                  file: reports/coverage/*.json
                  flags: frontend,backend
            - store_test_results:
                  path: reports
            - store_artifacts:
                  path: reports
            - store_artifacts:
                  path: errorShots
            - save_cache:
                  key: dependency-cache-linux-{{ checksum "yarn.lock" }}
                  paths:
                      - node_modules
                      - ~/.cache/yarn
            # Commented out till we need to process the assets after the fact.
            # Typically in like a deploy step.
            # - persist_to_workspace:
            #       root: .
            #       paths:
            #           - .git
            #           - package.json
            #           - oclif.manifest.json
            #           - yarn.lock
            #           - README.md
            #           - bin
            #           - dist
            #           - modules
            #           - lib
    build-and-test-win:
        executor: win/default
        steps:
            - checkout
            - restore_cache:
                  key: dependency-cache-win-{{ checksum "yarn.lock" }}
            - run:
                  shell: bash.exe
                  command: |
                      node --version
                      npm install -g sfdx-cli@latest
                      sfdx --version
            - run:
                  name: 'Authenticate to local dev testing org'
                  shell: bash.exe
                  command: |
                      echo $SFDX_CI_LOCALDEV_JWTKEY | base64 --decode > localdev.key
                      sfdx force:auth:jwt:grant --clientid ${SFDX_CI_LOCALDEV_CLIENTID} --username ${SFDX_CI_LOCALDEV_USERNAME} --jwtkeyfile localdev.key --setdefaultusername --setalias localdev
                      # rm localdev.key
                      sfdx force:auth:list
            - run:
                  shell: bash.exe
                  command: |
                      choco install googlechrome --ignore-checksums
            - run: yarn install --frozen-lockfile
            - run: yarn build
            - run: yarn test:ci
            - run:
                  shell: bash.exe
                  command: |
                      yarn test:e2e-ci
            - store_test_results:
                  path: reports
            - store_artifacts:
                  path: reports
            - store_artifacts:
                  path: errorShots
            - save_cache:
                  key: dependency-cache-win-{{ checksum "yarn.lock" }}
                  paths:
                      - node_modules
                      - ~/.cache/yarn

workflows:
    version: 2.1
    build_and_test:
        jobs:
            - build-and-test-linux
            - build-and-test-win:
                  context: vscode-test
