name: store-results
runs:
  using: composite
  steps:
  - uses: actions/upload-artifact@v2
    with:
      path: reports
  - uses: actions/upload-artifact@v2
    with:
      path: reports
  - uses: actions/upload-artifact@v2
    with:
      path: errorShots