version: 2
jobs:
  build_and_test:
    working_directory: ~/todomvc

    docker:
      - image: circleci/node:8.12-stretch-browsers

    steps:
      - checkout

      - restore_cache:
          keys:
          - yarn-v1-{{ checksum "yarn.lock" }}

      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - ~/.cache/yarn
            - node_modules
          key: yarn-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Run Linting
          command: yarn lint

      - run:
            name: Run Build
            command: yarn build

      - run:
          name: Run Unit Tests
          command: yarn test:unit --ci --maxWorkers=2

      - run:
          name: Run Integration Tests
          command: yarn test:integration

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
